### ISSUE TITLE
stub_request that works with CRAN version but not development version (with reprex)

### ISSUE THREAD

**Issue by mdneuzerling** [ropensci/webmockr#139]
Hi folks. I'm the maintainer of the `lambdr` package. I was informed about some broken tests in my package with the development version of `webmockr`.

I've narrowed the issue down to the reprex at the bottom of this issue. This reprex works on the latest CRAN version of `webmockr`, but fails on the current Github version ([ba664b3](https://github.com/ropensci/webmockr/commit/ba664b304921397bf65fb1ba166fef0396058dda)) with the following error:

```
Error:
! Real HTTP connections are disabled.
! Unregistered request:
ℹ POST:  http://red_panda/response  with body {{"parity":"odd"}}  with headers {Accept: application/json, text/xml, application/xml, */*, Content-Type: }

You can stub this request with the following snippet:
 stub_request('post', uri = 'http://red_panda/response') %>%
     wi_th(
       headers = list('Accept' = 'application/json, text/xml, application/xml, */*', 'Content-Type' = ''),
       body = list({"parity":"odd"})
     )

registered request stubs:
 POST: http://red_panda/response   with body {"parity":"odd"}  | to_return:    with status 200
```

The issue is definitely within the body of the stub. If you omit the `body` argument then everything works fine. Bizarrely, when I investigate the stub registry, I can see that the expected body and the body I'm posting are identical.

Could you please help me identify what's going on?

```r
webmockr::enable(quiet = TRUE)
webmockr::stub_registry_clear()

endpoint <- "http://red_panda/response"
# this is stringified JSON, although the error suggests that webmockr expects a list
response_body <- as.character(jsonlite::toJSON(list(parity = "odd"), auto_unbox = TRUE))

webmockr::stub_request("post", endpoint) |>
  webmockr::wi_th(
    body = response_body
  ) |>
  webmockr::to_return(status = 200) # most likely doesn't make a difference

httr::POST(
  url = endpoint,
  body = response_body
)
```

**Comment by sckott** [comment]
Thanks very much for this! I was kinda hoping for this but didn't actually ask. I'll dig in soon ...

**Comment by sckott** [comment]
@mdneuzerling hey i think i fixed it. can you install from main here and try running your tests agaan? works for me locally. and ran revdep checks and all good for all other revdeps

**Comment by mdneuzerling** [comment]
Thanks @sckott. I can confirm the reprex above is working fine with the main branch now, but I'm still getting test errors with `lambdr`. I'll look into it.

**Comment by sckott** [comment]
Thanks for looking into it

**Comment by sckott** [comment]
@mdneuzerling  

> I'm still getting test errors with `lambdr`

Are they related to `webmockr`?  I can't reproduce any test errors with `lambdr`

**Comment by mdneuzerling** [comment]
Huh. You're right. 0 errors. Maybe I forgot to refresh the R session?

In any case, I think we can call this one closed now. Thank you for your help!

**Comment by sckott** [comment]
Thanks for checking again!
